version: "3.8"

services:
  # Postgres
  postgres:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - app

  # BoxyHQ SAML Jackson
  jackson:
    image: "boxyhq/jackson:1.7.5"
    platform: linux/amd64
    depends_on:
      - postgres
    ports:
      - 5225:5225
    environment:
      - JACKSON_API_KEYS=secret #Don't use this secret in production
      - DB_ENGINE=sql
      - DB_TYPE=postgres
      - DB_URL=postgres://postgres:postgres@postgres:5432/postgres
      - NEXTAUTH_SECRET=secret #Don't use this secret in production
      - NEXTAUTH_URL=http://localhost:5225
    networks:
      - app

  # Cerbos
  cerbos:
    image: ghcr.io/cerbos/cerbos:0.24.0
    # platform: linux/amd64
    ports:
      - 3592:3592
      - 3593:3593
    volumes:
      - ./cerbos/config:/config
      - ./cerbos/policies:/policies
    command: server --config=/config/conf.yaml
    networks:
      - app

networks:
  app:

volumes:
  db_data:
